############# English navigation ##############

# main menu
[[main]]
name = "Home"
pageRef = "/"
weight = 1

[[main]]
name = "Roadmap"
pageRef = "/roadmap"
weight = 2

[[main]]
name = "Support"
pageRef = "/support"
weight = 3

# footer menu
[[footer]]
name = "Impressum"
pageRef = "/impressum"
weight = 1
