############# English navigation ##############

# main menu
[[main]]
name = "Home"
pageRef = "/"
weight = 1

[[main]]
name = "FAQ"
pageRef = "/faq"
weight = 2

[[main]]
name = "Pricing"
pageRef = "/pricing"
weight = 3

[[main]]
name = "Roadmap"
pageRef = "/roadmap"
weight = 4

[[main]]
name = "Support"
pageRef = "/support"
weight = 5

# footer menu
[[footer]]
name = "Contact"
pageRef = "/contact"
weight = 1

[[footer]]
name = "Privacy Policy"
pageRef = "/privacypolicy"
weight = 2

[[footer]]
name = "Terms of use"
pageRef = "/termsofuse"
weight = 3
